### PR TITLE
Publicly accessible `session_id` of `Client`

### PR DESCRIPTION
**Pull request by SValkanov**
Make the instance variable `session_id` publicly accessible(setter) for `SalesforceBulk::Client`.
Allow `instance_host` and `session_id` in object initialization.

The ability to set `session_id` would allow to leverage caching the session and setting it directly when needed, instead of doing `#authenticate` request on each client initialization.

### CODE REVIEW

**Comment by javierjulio** [comment]
@SValkanov thanks! A few questions. Why the need to set the `instance_host` through the initializer? I guess the need for that too is because it's reset reset to `nil` in the `authenticate` method right? I haven't worked with this in ages. Why the need to cache the session? Is it really that costly of a request?

**Comment by SValkanov** [comment]
@javierjulio, Thank you for the reply.

> Why the need to set the instance_host through the initializer?

The `instance_host` is currently set automatically through the `#authenticate` method. If we do not use the authenticate method, there would be no way to set the `instance_host`.
https://github.com/javierjulio/salesforce_bulk/blob/cdf065fdecd34c5885558597688e292ab5e51878/lib/salesforce_bulk/client.rb#L64

> Why the need to cache the session? Is it really that costly of a request?

Not that it is that costly, however it is an additional request, which could be optionally omitted. In some cases could cause a significant cost. It is counted against the API usage limits. Apart from that it would make the Client more flexible without changing the logic around it.

**Comment by javierjulio** [comment]
@SValkanov thanks! I don't see an alternative that wouldn't require more substantial changes so I'm fine with this and I can see how this would help make things easier for you.

**Review by javierjulio — APPROVED** [review]

**Comment by javierjulio** [comment]
@SValkanov I released v4.0.3 with this change. Thanks again!

**Pull request merged**
