### PR TITLE
Update to newest rubies and use faster Travis infrastructure

### PR DESCRIPTION
**Pull request by pschambacher**
@javierjulio

### CODE REVIEW

**Comment by javierjulio** [comment]
@pschambacher would you be able to add Ruby 2.2.x as well? I currently run everything on Ruby 2.2.x so if we are upgrading to all the new Rubies might as well include that.

**Comment by pschambacher** [comment]
Ruby 2.2 and ActiveSupport 3.2 are not compatible but I can get 4.0 working with 2.2

**Comment by pschambacher** [comment]
2.x only now.

**Comment by javierjulio** [comment]
@pschambacher no problem, that sounds good to me. Best to keep Ruby and dependencies current. I'm very big on that. Great thanks!

**Comment by pschambacher** [comment]
This is green now, if you could merge I can rebase the compat one and get it working on recent rubies

**Comment by javierjulio** [comment]
@pschambacher done, thanks!

**Pull request merged**
