### PR TITLE
Compatibility with Rails 4.0, 4.1 and 4.2 and Ruby 2.2

### PR DESCRIPTION
**Pull request by pschambacher**
@javierjulio

### CODE REVIEW

**Comment by javierjulio** [comment]
@pschambacher thank you! Waiting on Travis to report that all PR's are passing. When checking Travis for this PR though it shows its using Ruby 1.8.7, 1.9.2, and 1.9.3. I don't have a problem with just supporting Ruby 2.x on a new release unless you'd at least like to have 1.9.3 and up.

**Comment by pschambacher** [comment]
@javierjulio No we're running 2.1 and 2.2 so we don't need 1.9
I can change the PR and keep only 2.x

**Comment by javierjulio** [comment]
@pschambacher awesome, lets do it. Ruby 2.x only!

**Comment by pschambacher** [comment]
@javierjulio Here, it's cutting edge now :)

**Comment by javierjulio** [comment]
❤️

**Comment by javierjulio** [comment]
@pschambacher awesome! Are you using this at @zendesk? I remember @dlee contributing a few years back and saw he also works at Zendesk. Big shout out to you both for contributing! So great knowing this gem is still useful after all this time. I didn't end up working with Salesforce for long.

I have plans tonight and tomorrow but this **will** go out as a 2.0 release on Sunday the latest. If you can update the README with a short blurb on what you changed that'd be great! If not I can get to it. I'll take care of incrementing the version and releasing.

**Comment by pschambacher** [comment]
@javierjulio I'll get a PR together for the README

**Pull request merged**
